### ISSUE TITLE
文章顶部 banner 图片如何设置？

### ISSUE THREAD

**Issue by ferocknew** [Mrminfive/hexo-theme-skapp#24]
如题

**Comment by BruceYuj** [comment]
根_config.yml中：`header_cover: http://oo12ugek5.bkt.clouddn.com/blog/images/banner-bg.jpg` ， readme.md中是有说明的。

**Comment by ferocknew** [comment]
感谢回答问题，并不是首页的banner ，而是每篇文章缩略图？麻烦了

**Comment by BruceYuj** [comment]
文章markdown文件头部添加`cover: picture link`

**Comment by ferocknew** [comment]
感谢，这个问题已解决，另一个问题想咨询你一下，

生成的文章单页，这里有一个 undefined，应该在文章 md，文件内增加什么标签？

![image](https://user-images.githubusercontent.com/2178683/33545801-39f40810-d91a-11e7-9adc-7999a1f45be4.png)

**Comment by BruceYuj** [comment]
```
---
title: Hello World
cover: http://oxnuwmm3w.bkt.clouddn.com/hello-world.jpeg
author: 
  nick: BruceYJ
  link: https://www.github.com/BruceYuj
---
```
