### ISSUE TITLE
可以在博客某个位置固定显示一个目录吗？

### ISSUE THREAD

**Issue by HPDell** [Mrminfive/hexo-theme-skapp#51]
你好~

可以在博客某个位置固定显示一个目录吗？这样可能看起来更方便一些。

**Comment by upupming** [comment]
可以在文章右侧的sidebar显示文章目录结构。

+ 在`/layout/_partial/common/sidebar.swig`的aside里面（与“最新文章”、“搜索”同一级）插入书签代码：
``` twig
<div class="post-toc">
        {{ toc(page.content) }}
</div>
```

+ 修改相应的scss文件美化显示，在`/source/scss/views/layout/_sidebar.scss`中插入：
```scss
.post-toc ol {
    margin: 0;
    padding: 0 2px 5px 10px;
    text-align: left;
    list-style: none;
    font-size: $main-fs;

    a {
        transition-property: all;
        color: $main-color;
        border-bottom-color: $main-color;

        &:hover {
            color: $main-color--hover;
            border-bottom-color: $main-color--hover;
        }
    }
}
```

测试结果如下图：
[![screenshot from 2018-03-17 23-03-55](https://user-images.githubusercontent.com/24741764/37556901-86b1ebe0-2a37-11e8-8aec-95726436b8ea.png)](https://upupming.site)
